let sourceFilter = initialStateValue('statsSource', 'all') || 'all';
let modelFilter = initialStateValue('statsModel', 'all') || 'all';
let analyticsProjectFilter = initialStateValue('statsProject', 'all') || 'all';
let rangeFilter = initialStateValue('statsRange', 'today') || 'today';
let customRangeDays = Math.max(2, Math.min(365, Number(initialStateValue('customRangeDays', '60')) || 60));
let customDateStart = Number(initialStateValue('customDateStart', 0)) || (rendererNow() - 86400000);
let customDateEnd = Number(initialStateValue('customDateEnd', 0)) || rendererNow();
let dateRangeOpen = false;
let dateRangeDraftStart = 0;
let dateRangeDraftEnd = 0;
let dateRangeError = '';
let dateRangeFocus = 'start';
let dateRangeMonth = Number(initialStateValue('dateRangeMonth', 0)) || 0;
let tableTab = initialStateValue('statsTableTab', 'requests') || 'requests';
let workspaceMode = 'analytics';
writeInitialStateValue('workspaceMode', workspaceMode);
let analyticsQuery = initialStateValue('statsAnalyticsQuery') || initialStateValue('statsQuery') || '';
let sessionQuery = initialStateValue('statsSessionQuery', '') || '';
let sessionStatusFilter = initialStateValue('sessionStatusFilter', 'active') || 'active';
let sessionSort = initialStateValue('sessionSort', 'updated') || 'updated';
let sessionTagFilter = initialStateValue('sessionTagFilter', 'all') || 'all';
let sessionQuickFilter = initialStateValue('sessionQuickFilter', 'all') || 'all';
let sessionProjectFilter = initialStateValue('sessionProjectFilter', 'all') || 'all';
let analyticsAdvancedOpen = initialStateValue('analyticsAdvancedOpen') === '1';
