package com.codearts.bar.toolwindow;

import com.codearts.bar.model.UsageSnapshot;
import com.codearts.bar.service.CodeArtsDataService;
import com.google.gson.JsonObject;
import com.intellij.openapi.Disposable;
import com.intellij.openapi.project.Project;
import com.intellij.openapi.ui.SimpleToolWindowPanel;
import com.intellij.ui.JBColor;
import com.intellij.ui.components.*;
import com.intellij.ui.table.JBTable;
import com.intellij.util.ui.JBUI;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.text.*;
import java.util.*;
import java.util.List;

final class CodeArtsDashboardPanel extends SimpleToolWindowPanel implements Disposable {
    private final Project project;
    private final JBLabel refreshState=new JBLabel("Waiting for data"),sessionPageLabel=new JBLabel("Page 1"),requestPageLabel=new JBLabel("Select a session");
    private final JProgressBar progress=new JProgressBar(0,100);
    private final JBLabel today=metric("--","Today tokens"),rolling=metric("--","Rolling window"),week=metric("--","7 days"),requests=metric("--","Today requests"),cache=metric("--","Cache hit"),health=metric("--","Health");
    private final TrendChartPanel chart=new TrendChartPanel();
    private final JComboBox<String> trendRange=new JComboBox<>(new String[]{"Last 24 hours","Last 14 days"});
    private final DefaultTableModel modelTable=model(new String[]{"Model","Provider","Tokens","Input","Output","Requests","Cache","Latency P95"});
    private final DefaultTableModel sourceTable=model(new String[]{"Source","Adapter","Tokens","Requests","Errors","Latency P95","Path"});
    private final DefaultTableModel sessionTable=model(new String[]{"Session","Source","Model","Tokens","Calls","Updated","Directory"});
    private final DefaultTableModel requestTable=model(new String[]{"Time","Session","Model","Source","Tokens","Latency","TTFT","Status"});
    private final JBTable sessionGrid=grid(sessionTable),requestGrid=grid(requestTable);
    private final JBTextArea diagnostics=new JBTextArea();
    private final JBTextField sessionSearch=new JBTextField(18);
    private AutoCloseable subscription;
    private UsageSnapshot current=UsageSnapshot.empty("Waiting for refresh");
    private List<UsageSnapshot.SessionInfo> sessionRows=List.of();
    private int sessionPage=1,sessionPageCount=1,requestPage=1,requestPageCount=1;
    private String selectedSessionId="";

    CodeArtsDashboardPanel(Project project){super(true,true);this.project=project;setToolbar(toolbar());setContent(content());trendRange.addActionListener(e->renderTrend());sessionGrid.getSelectionModel().addListSelectionListener(e->{if(!e.getValueIsAdjusting())selectSession();});subscription=CodeArtsDataService.getInstance().subscribe(this::render);CodeArtsDataService.getInstance().refresh(false);}
    private JComponent toolbar(){JPanel p=new JPanel(new FlowLayout(FlowLayout.LEFT,7,4));JButton refresh=button("Refresh",()->{refreshState.setText("Refreshing...");CodeArtsDataService.getInstance().refresh(true);});JButton settings=button("Settings",()->com.intellij.openapi.options.ShowSettingsUtil.getInstance().showSettingsDialog(project,"CodeArts Bar"));JButton folder=button("Open data folder",com.codearts.bar.actions.OpenDataFolderAction::openFolder);p.add(refresh);p.add(settings);p.add(folder);p.add(refreshState);return p;}
    private JComponent content(){JTabbedPane tabs=new JBTabbedPane();tabs.addTab("Overview",overview());tabs.addTab("Trend",trend());tabs.addTab("Models",table(grid(modelTable)));tabs.addTab("Sources",table(grid(sourceTable)));tabs.addTab("Sessions",sessionsPanel());tabs.addTab("Diagnostics",diagnosticsPanel());return tabs;}
    private JComponent overview(){JPanel root=new JPanel(new BorderLayout());JPanel cards=new JPanel(new GridLayout(2,3,8,8));cards.setBorder(JBUI.Borders.empty(12));for(JBLabel x:new JBLabel[]{today,rolling,week,requests,cache,health})cards.add(card(x));JPanel quota=new JPanel(new BorderLayout(8,5));quota.setBorder(JBUI.Borders.empty(0,12,12,12));progress.setStringPainted(true);quota.add(new JBLabel("Daily display limit"),BorderLayout.WEST);quota.add(progress);root.add(cards,BorderLayout.NORTH);root.add(quota,BorderLayout.CENTER);return root;}
    private JComponent trend(){JPanel p=new JPanel(new BorderLayout());JPanel head=new JPanel(new FlowLayout(FlowLayout.LEFT));head.add(new JBLabel("Range:"));head.add(trendRange);p.add(head,BorderLayout.NORTH);p.add(chart);return p;}
    private JComponent sessionsPanel(){JPanel upper=new JPanel(new BorderLayout());JPanel bar=new JPanel(new FlowLayout(FlowLayout.LEFT));bar.add(new JBLabel("Search:"));bar.add(sessionSearch);bar.add(button("Apply",()->{sessionPage=1;loadSessionPage();}));bar.add(button("Previous",()->{if(sessionPage>1){sessionPage--;loadSessionPage();}}));bar.add(button("Next",()->{if(sessionPage<sessionPageCount){sessionPage++;loadSessionPage();}}));bar.add(sessionPageLabel);upper.add(bar,BorderLayout.NORTH);upper.add(table(sessionGrid));JPanel lower=new JPanel(new BorderLayout());JPanel requestBar=new JPanel(new FlowLayout(FlowLayout.LEFT));requestBar.add(button("Previous requests",()->{if(requestPage>1){requestPage--;loadRequestPage();}}));requestBar.add(button("Next requests",()->{if(requestPage<requestPageCount){requestPage++;loadRequestPage();}}));requestBar.add(requestPageLabel);lower.add(requestBar,BorderLayout.NORTH);lower.add(table(requestGrid));JSplitPane split=new JSplitPane(JSplitPane.VERTICAL_SPLIT,upper,lower);split.setResizeWeight(.5);split.setBorder(null);return split;}
    private JComponent diagnosticsPanel(){diagnostics.setEditable(false);diagnostics.setLineWrap(true);diagnostics.setWrapStyleWord(true);diagnostics.setBorder(JBUI.Borders.empty(12));JPanel p=new JPanel(new BorderLayout());p.add(button("Copy redacted report",()->{diagnostics.selectAll();diagnostics.copy();diagnostics.select(0,0);}),BorderLayout.NORTH);p.add(new JBScrollPane(diagnostics));return p;}
    private void render(UsageSnapshot s){current=s;if(!s.ok()){refreshState.setText("Read failed");refreshState.setForeground(JBColor.RED);diagnostics.setText(s.error()+"\n\nConfigure Node.js and CodeArts Bar in Settings | Tools | CodeArts Bar.");return;}refreshState.setForeground(JBColor.foreground());refreshState.setText("Updated "+s.updatedAt()+" | "+s.adapter());today.setText(html(tokens(s.today().total()),"Today tokens"));rolling.setText(html(tokens(s.window().total()),"Rolling window"));week.setText(html(tokens(s.week().total()),"7 days"));requests.setText(html(number(s.today().messages()),"Today requests"));cache.setText(html(percent(s.today().cacheHitRate()),"Cache hit"));health.setText(html(empty(s.health().label(),"OK"),empty(s.health().message(),"Health")));int pct=(int)Math.max(0,Math.min(100,Math.round(s.usagePercent())));progress.setValue(pct);progress.setString(pct+"% | "+tokens(s.quota().used())+(s.quota().limit()==null?"":" / "+tokens(s.quota().limit())));renderTrend();fillModels(s.models());fillSources(s.sources());renderDiagnostics(s);sessionPage=1;loadSessionPage();}
    private void loadSessionPage(){List<String> args=new ArrayList<>(List.of("--page",Integer.toString(sessionPage),"--page-size","50"));CodeArtsDataService.getInstance().query("sessions",args,data->{sessionRows=UsageSnapshot.sessionItems(data);sessionPageCount=Math.max(1,intValue(data,"pageCount",1));sessionPageLabel.setText("Page "+sessionPage+" / "+sessionPageCount+" | "+intValue(data,"total",0)+" sessions");String query=sessionSearch.getText().trim().toLowerCase(Locale.ROOT);List<UsageSnapshot.SessionInfo> filtered=query.isEmpty()?sessionRows:sessionRows.stream().filter(x->(x.title()+" "+x.directory()+" "+x.model()).toLowerCase(Locale.ROOT).contains(query)).toList();fillSessions(filtered);},this::showQueryError);}
    private void selectSession(){int view=sessionGrid.getSelectedRow();if(view<0)return;int row=sessionGrid.convertRowIndexToModel(view);if(row<0||row>=sessionRows.size())return;selectedSessionId=sessionRows.get(row).id();requestPage=1;loadRequestPage();}
    private void loadRequestPage(){if(selectedSessionId.isBlank())return;CodeArtsDataService.getInstance().query("requests",List.of("--session-id",selectedSessionId,"--page",Integer.toString(requestPage),"--page-size","100"),data->{fillRequests(UsageSnapshot.requestItems(data));requestPageCount=Math.max(1,intValue(data,"pageCount",1));requestPageLabel.setText("Requests page "+requestPage+" / "+requestPageCount+" | "+intValue(data,"total",0));},this::showQueryError);}
    private void showQueryError(String message){refreshState.setText("Query failed: "+message);refreshState.setForeground(JBColor.RED);}
    private void renderTrend(){if(current.ok()){boolean hourly=trendRange.getSelectedIndex()==0;chart.setData(hourly?current.hourlyTrend():current.dailyTrend(),hourly);}}
    private void fillModels(List<UsageSnapshot.ModelUsage> rows){clear(modelTable);for(var x:rows)modelTable.addRow(new Object[]{empty(x.name(),x.model()),x.provider(),x.total(),x.input(),x.output(),x.requests(),percent(x.cacheHitRate()),duration(x.latencyP95())});}
    private void fillSources(List<UsageSnapshot.SourceInfo> rows){clear(sourceTable);for(var x:rows)sourceTable.addRow(new Object[]{x.label(),x.adapter(),x.total(),x.requests(),x.errors(),duration(x.latencyP95()),x.dbPath()});}
    private void fillSessions(List<UsageSnapshot.SessionInfo> rows){clear(sessionTable);for(var x:rows)sessionTable.addRow(new Object[]{empty(x.title(),"Untitled"),x.source(),x.model(),x.total(),x.requests(),date(x.updatedAt()),x.directory()});}
    private void fillRequests(List<UsageSnapshot.RequestInfo> rows){clear(requestTable);for(var x:rows)requestTable.addRow(new Object[]{date(x.time()),x.sessionTitle(),x.model(),x.source(),x.total(),duration((double)x.latencyMs()),duration(x.ttftMs()),x.success()?"OK":Integer.toString(x.status())});}
    private void renderDiagnostics(UsageSnapshot s){StringBuilder b=new StringBuilder();b.append("HEALTH\n").append(s.health().label()).append(" | ").append(s.health().message()).append('\n');for(String issue:s.health().issues())b.append(" - ").append(issue).append('\n');b.append("\nDATABASE\nName: ").append(new java.io.File(s.dbPath()).getName()).append("\nPath hash: ").append(Integer.toHexString(s.dbPath().hashCode())).append("\nSize: ").append(number(s.dbSize())).append(" bytes\nAdapter: ").append(s.adapter()).append("\nProtocol: ").append(s.protocolVersion());b.append("\n\nPERFORMANCE\nSamples: ").append(number(s.performance().samples())).append("\nErrors: ").append(number(s.performance().errors())).append("\nLatency avg / P95: ").append(duration(s.performance().latencyAvg())).append(" / ").append(duration(s.performance().latencyP95())).append("\nTTFT avg / P95: ").append(duration(s.performance().ttftAvg())).append(" / ").append(duration(s.performance().ttftP95()));b.append("\n\nQUEUE\nSamples: ").append(number(s.queue().samples())).append("\nAverage / P95 / Max: ").append(duration(s.queue().avgMs())).append(" / ").append(duration(s.queue().p95Ms())).append(" / ").append(duration(s.queue().maxMs()));b.append("\n\nSESSIONS\nTotal: ").append(number(s.sessionTotal())).append("\nActive: ").append(number(s.sessionActive()));b.append("\n\nQUOTA NOTE\n").append(s.quota().note());diagnostics.setText(b.toString());diagnostics.setCaretPosition(0);}
    private static int intValue(JsonObject o,String key,int fallback){try{return o.has(key)?o.get(key).getAsInt():fallback;}catch(Exception ignored){return fallback;}}
    private static JButton button(String text,Runnable action){JButton b=new JButton(text);b.addActionListener(e->action.run());return b;}private static JBTable grid(DefaultTableModel m){JBTable t=new JBTable(m);t.setAutoCreateRowSorter(true);t.setStriped(true);t.setFillsViewportHeight(true);t.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);return t;}private static JComponent table(JBTable t){return new JBScrollPane(t);}private static DefaultTableModel model(String[] cols){return new DefaultTableModel(cols,0){@Override public boolean isCellEditable(int r,int c){return false;}@Override public Class<?> getColumnClass(int c){for(int r=0;r<getRowCount();r++){Object v=getValueAt(r,c);if(v!=null)return v.getClass();}return Object.class;}};}private static void clear(DefaultTableModel m){m.setRowCount(0);}private static JBLabel metric(String v,String c){JBLabel l=new JBLabel(html(v,c));l.setHorizontalAlignment(SwingConstants.CENTER);return l;}private static JPanel card(JComponent c){JPanel p=new JPanel(new BorderLayout());p.setBorder(JBUI.Borders.compound(JBUI.Borders.customLine(JBColor.border()),JBUI.Borders.empty(15)));p.add(c);return p;}private static String html(String v,String c){return "<html><div style='text-align:center'><span style='font-size:19px;font-weight:bold'>"+v+"</span><br><span style='color:#888888'>"+c+"</span></div></html>";}private static String number(long n){return new DecimalFormat("#,##0").format(n);}private static String tokens(long n){if(n>=1_000_000)return new DecimalFormat("0.00M").format(n/1_000_000d);if(n>=1_000)return new DecimalFormat("0.0K").format(n/1_000d);return number(n);}private static String percent(Double n){return n==null?"--":new DecimalFormat("0.0").format(n)+"%";}private static String duration(Double n){return n==null?"--":n>=1000?new DecimalFormat("0.00s").format(n/1000):new DecimalFormat("0ms").format(n);}private static String date(long ms){return ms<=0?"--":DateFormat.getDateTimeInstance(DateFormat.SHORT,DateFormat.SHORT).format(new Date(ms));}private static String empty(String s,String f){return s==null||s.isBlank()?f:s;}
    @Override public void dispose(){if(subscription!=null)try{subscription.close();}catch(Exception ignored){}}
}
